{
 "title": "Rate Limiter Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Traffic Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests - Allowed vs Rejected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (result) (ratelimit_request_total)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Rejection Rate per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(ratelimit_request_total{result=\"rejected\"}[1m])",
     "legendFormat": "{{clientType}}"
    }
   ]
  },
  {
   "title": "Requests by Client Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(ratelimit_request_total[1m])",
     "legendFormat": "{{clientType}} - {{result}}"
    }
   ]
  }
 ]
}